[[news]]
date = "2026-09"
content = "在西班牙-中国联合研究组第五次国际会议（拉科鲁尼亚大学）作大会主题报告“疗愈环境与神经建筑学 Healing Environments and Neuro-architecture” 🇪🇸"

[[news]]
date = "2025-12"
content = "入职同济大学建筑与城市规划学院神经与增强建筑实验室，任博士后研究员 🎉"

[[news]]
date = "2025-11"
content = "完成同济大学建筑学工学博士学业，并获评上海市优秀毕业生"

[[news]]
date = "2025-01"
content = "论文《Neurological benefits of third places for young adults in healthy urban environments》发表于 Frontiers of Architectural Research"

[[news]]
date = "2024-03"
content = "作为项目负责人获唐仲英基金会国际博士研究基金资助"
