[[news]]
date = "2025-12"
content = "入职同济大学建筑与城市规划学院神经与增强建筑实验室，任博士后研究员 🎉"

[[news]]
date = "2025-11"
content = "完成同济大学建筑学工学博士学业，并获评上海市优秀毕业生"

[[news]]
date = "2025-06"
content = "在新加坡设计与健康世界大会（World Congress on Design and Health）报告第三空间对青年神经与情绪福祉的促进机制"

[[news]]
date = "2025-01"
content = "论文《Neurological benefits of third places for young adults in healthy urban environments》发表于 Frontiers of Architectural Research"

[[news]]
date = "2024-03"
content = "作为项目负责人获唐仲英基金会国际博士研究基金资助"
